# GitHub Actions Workflow for CI/CD

name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:

  # -------------------------------
  # CI JOB
  # -------------------------------

  build-and-push:

    runs-on: ubuntu-latest      # GitHub creates temporary Ubuntu VM

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3

        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # Docker Hub Username
          password: ${{ secrets.DOCKER_TOKEN }}      # Docker Hub Token

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5

        with:
          context: .                                 # Current Project Folder
          push: true                                 # Push image to Docker Hub
          tags: vedantv0502/staysphere:latest        # Docker Image Name


  # -------------------------------
  # CD JOB
  # -------------------------------

  deploy:

    needs: build-and-push         # Wait until CI finishes successfully

    runs-on: self-hosted          # Use Vedant's Laptop

    steps:

      - name: Restart Kubernetes Deployment

        run: kubectl rollout restart deployment/staysphere-deployment
        # Create New Pod
        # New Pod pulls latest Docker Image


# ------------------------------------------------------
# COMPLETE FLOW
# ------------------------------------------------------
#
# Developer
#     ↓
# git push
#     ↓
# GitHub Actions
#     ↓
# Build Docker Image
#     ↓
# Push Docker Image
#     ↓
# Self Hosted Runner
#     ↓
# kubectl rollout restart
#     ↓
# Kubernetes
#     ↓
# New Pod
#     ↓
# Latest StaySphere Running
#
# ------------------------------------------------------
#
# WITHOUT CI/CD:
#
# git push
# docker build
# docker push
#
# WITH CI/CD:
#
# git push
# That's it 😎
# GitHub does the rest automatically.
#
# ------------------------------------------------------


# ------------------------------------------------------
# When you did:

# git push

# GitHub automatically:

# 1. Created Ubuntu Machine
#         ↓
# 2. Downloaded StaySphere Code
#         ↓
# 3. Logged into Docker Hub
#         ↓
# 4. Built Docker Image
#         ↓
# 5. Pushed Image to Docker Hub
#         ↓
# 6. Destroyed Ubuntu Machine

# All automatically.
# ------------------------------------------------------

# ------------------------------------------------------
# kubectl rollout restart deployment/staysphere-deployment - command

# Kubernetes does:

# Current Pod
#     staysphere-v1
#          ↓
# Create New Pod
#     staysphere-v2
#          ↓
# Wait Until Ready
#          ↓
# Delete Old Pod
# ------------------------------------------------------








# RUNNER
# ------------------------------------------------------
# Runner Group
# Purpose:
# Organize multiple Self Hosted Runners.

# For learning and single laptop:
# Press ENTER to use Default.
# ------------------------------------------------------


# ------------------------------------------------------
# Would you like to run the runner as service?

# Y = Start automatically with Windows

# N = Start manually

# For learning:
# Press ENTER (N)
#------------------------------------------------------



#--------------After Runner is Applyed ------------------------------
  
            #       GitHub
            #          │
            #          ▼
            # Self Hosted Runner
            #    (Your Laptop)
            #          │
            #          ▼
            #      Minikube
            #          │
            #          ▼
            #    Kubernetes
            #          │
            #          ▼
            #         Pod
# ------------------------------------------------------

